### ISSUE TITLE
when "matcha build gomatcha.io/matcha/examples" missing file java

### ISSUE THREAD

**Issue by bakatest-me** [gomatcha/matcha#20]
src/gomatcha.io/matcha/cmd/GoValue.java: no such file or directory
src/gomatcha.io/matcha/cmd/Bridge.java: no such file or directory
src/gomatcha.io/matcha/cmd/Tracker.java: no such file or directory

**Comment by overcyn** [comment]
Did you run `go install` and then update the git repo after? Maybe try running `go install` again?

**Comment by bakatest-me** [comment]
I'm not sure but now i use ./bin/matcha build gomatcha.io/matcha/examples it work 
( my project directory is not in default $GOPATH but new $GOPATH dir )

**Comment by overcyn** [comment]
Closing since it works now.
