### ISSUE TITLE
i think example in getting-started is wrong (ios)

### ISSUE THREAD

**Issue by bakatest-me** [gomatcha/matcha#23]
from
MatchaGoValue *rootVC = [[[MatchaGoValue alloc] initWithFunc:@"github.com/overcyn/tutorial New"] call:nil **args:nil][0];**
to 
MatchaGoValue *rootVC = [[[MatchaGoValue alloc] initWithFunc:@"github.com/overcyn/tutorial New"] call:nil  **_, nil][0];_**

**Comment by overcyn** [comment]
Thanks for catching that. Fixed now on website.
