### ISSUE TITLE
ubuntu no xcode

### ISSUE THREAD

**Issue by bsed** [gomatcha/matcha#43]
kelvin@gnux:~/gocode/src/ah> matcha init                                                                                                                                                            (10/16 20:15:11)
Xcode not available

**Comment by overcyn** [comment]
Yeah no Linux support yet.

**Comment by 1l0** [comment]
dupl: https://github.com/gomatcha/matcha/issues/7

**Comment by bsed** [comment]
@1l0  thank you~
