### ISSUE TITLE
Linux and Windows support for Android only development

### ISSUE THREAD

**Issue by XanthusL** [gomatcha/matcha#7]
Matcha is awesome though it's in early development. But I don't have any MacOS devices.

**Comment by overcyn** [comment]
Yes, I think it shouldn't be too difficult to add.

**Comment by Omar-Elrefaei** [comment]
Waiting for Linux 👍

**Comment by Deluxo** [comment]
dis.

**Comment by mjgarton** [comment]
Is there any information available which might make it easy to understand how to add Linux support?  I'd be happy to help out in adding Linux support, but it's not immediately obvious what needs to be done.

**Comment by overcyn** [comment]
I don't know what issues you will run into. But I would run update to latest. Run go install and then `matcha init --targets="android"` and `matcha build --targets="android" gomatcha.io/matcha/examples`. And just see what errors you get from there. I'm guessing some directories might be layed out a little differently, or environmental variables might be different. I don't know. And then modify `cmd/init.go` and `cmd/bind.go` to get them working.

**Comment by Icecream-blue-sky** [comment]
so we can't use matcha in Windows?

**Comment by overcyn** [comment]
No not at the moment. But I will try to get support in soon.

**Comment by bsed** [comment]
kelvin@gnux:~/gocode/src> matcha init --targets="android"
go install -pkgdir=/home/kelvin/gocode/pkg/matcha/pkg_android_arm std failed: exit status 2
# runtime/cgo
_cgo_export.c:2:10: fatal error: 'stdlib.h' file not found

**Comment by Omar-Elrefaei** [comment]
I am working on linux port, got rid of all Xcode errors, but didn't have time to try it yet. 🙃

Will report back ASAP ☺

Windows SHOULD be easy after Linux 😉

**Comment by bsed** [comment]
@Omar-Elrefaei I compile examples in windows10, perfect operation, please paste detailed error information. 
![image](https://user-images.githubusercontent.com/10845087/31760548-9eaf02ca-b4e7-11e7-9eec-a65d80b2c669.png)

**Comment by overcyn** [comment]
I've merged in Windows and Linux support (only tested on Ubuntu). https://github.com/gomatcha/matcha/pull/50
